[package]
name = "confused"
version = "0.1.0"
edition = "2021"
description = "treat scary functions with the respect they deserve"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = "2.0.77"